def test_失敗する():
    assert 1 == 0
